# Generated by Django 3.2.8 on 2021-10-28 11:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('ic_pp', models.CharField(max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='IC/Passport No.')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('residential_address', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_address', models.CharField(blank=True, max_length=100, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,12}$')])),
                ('ethnicity', models.CharField(choices=[('African', 'African'), ('American', 'American'), ('European', 'European'), ('Asian', 'Asian')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PatientBreast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Breast_Img', models.ImageField(upload_to='Hospital/BreastImages/')),
                ('BreastSide', models.CharField(blank=True, choices=[('L', 'Left'), ('R', 'Right')], default='L', max_length=1)),
                ('ViewType', models.CharField(blank=True, choices=[('MLO', 'Mediolateral Oblique'), ('CC', 'Craniocaudal')], default='MLO', max_length=3)),
                ('Density', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('DateTaken', models.DateTimeField(auto_now_add=True, null=True)),
                ('prediction', models.CharField(blank=True, max_length=10)),
                ('predicted_img', models.ImageField(null=True, upload_to='Hospital/BreastImages/')),
                ('seg_results', models.CharField(blank=True, max_length=20, null=True)),
                ('Patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital.patient')),
            ],
            options={
                'ordering': ['Patient', 'DateTaken'],
            },
        ),
    ]
